-d C:\Users\vegad\Desktop\fpga_ArtificialVision\Final Project\impl\gwsynthesis\fpga_artificialvision_project.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\Users\vegad\Desktop\fpga_ArtificialVision\Final Project\src\pinout.cst
-cfg C:\Users\vegad\Desktop\fpga_ArtificialVision\Final Project\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-place_option 0
-route_option 0
-clock_route_order 0
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
