-d C:\Users\vegad\Desktop\tang\counter\impl\gwsynthesis\counter.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\Users\vegad\Desktop\tang\counter\src\counter.cst
-cfg C:\Users\vegad\Desktop\tang\counter\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
