-d C:\Users\vegad\Desktop\tang\flipflip_btn_led\impl\gwsynthesis\flipflip_btn_led.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\Users\vegad\Desktop\tang\flipflip_btn_led\src\flipflip_btn_led.cst
-cfg C:\Users\vegad\Desktop\tang\flipflip_btn_led\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
