-d C:\Users\vegad\Desktop\tang\flipflop_btn_led_GAO\impl\gwsynthesis\flipflop_btn_led_GAO.vg
-p GW2AR-18C-QFN88-8
-pn GW2AR-LV18QN88C8/I7
-cst C:\Users\vegad\Desktop\tang\flipflop_btn_led_GAO\src\flipflop_btn_led_GAO.cst
-cfg C:\Users\vegad\Desktop\tang\flipflop_btn_led_GAO\impl\pnr\device.cfg
-gao_crc 1100110110110110
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-rtl_gao
